# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'YakAl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DropDown'
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리

  # Pods for YakAl

end
