// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QKLUZnSRAioz7JtMYqPErbFDTnW4h3Q',
    appId: '1:469080203233:web:eeca1ea41845a4583bbca0',
    messagingSenderId: '469080203233',
    projectId: 'yakal-fdd3d',
    authDomain: 'yakal-fdd3d.firebaseapp.com',
    storageBucket: 'yakal-fdd3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkPO4mAfa8wiH3REmAAUwl27lCkkyhgfQ',
    appId: '1:469080203233:android:8df7a46a722e78853bbca0',
    messagingSenderId: '469080203233',
    projectId: 'yakal-fdd3d',
    storageBucket: 'yakal-fdd3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6pfL5g_yn7A9zMg_VWphhr24DiGS-lwI',
    appId: '1:469080203233:ios:703a0865b2a92a443bbca0',
    messagingSenderId: '469080203233',
    projectId: 'yakal-fdd3d',
    storageBucket: 'yakal-fdd3d.appspot.com',
    iosBundleId: 'com.viewpharm.yakal.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6pfL5g_yn7A9zMg_VWphhr24DiGS-lwI',
    appId: '1:469080203233:ios:8a9dd077fe8d31f03bbca0',
    messagingSenderId: '469080203233',
    projectId: 'yakal-fdd3d',
    storageBucket: 'yakal-fdd3d.appspot.com',
    iosBundleId: 'com.example.yakal.RunnerTests',
  );
}
